name: PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
env:
  GEMINI_MODEL: "gemini-1.5-pro-latest"


jobs:
  gitleaks-scan:
    name: Checking for hardcoded secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  static-analysis:
    name: Static Code Analysis
    runs-on: ubuntu-latest

    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: go

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
  
  scan-dependencies:
    name: Check Dependencies Vulnerabilities
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: anchore/scan-action@v3
        with:
          path: "."
          fail-build: true
  ai-review:
    runs-on: ubuntu-latest
    needs: [gitleaks-scan, scan-dependencies]
    permissions:
      contents: read
      pull-requests: write
    name: AI review
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: Stone-IT-Cloud/gemini-code-review-action@0.0.2
        name: "Code Review by Gemini AI"
        id: review
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repository: ${{ github.repository }}
          github_pull_request_number: ${{ github.event.pull_request.number }}
          git_commit_hash: ${{ github.event.pull_request.head.sha }}
          model: ${{ env.GEMINI_MODEL }}
          pull_request_diff: ${{ github.event.pull_request.diff }}
          extra_prompt: |-
            Please write your review in English as an experienced Golang developer.
          log_level: "INFO"
      - name: Check for errors (example)
        if: steps.review.outcome != 'success'
        run: |
          echo "Gemini review failed!"
          exit 1